---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: teamdagpenger
  name: dp-monitor-pods
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - configmaps
    verbs:
      - get
      - watch
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: teamdagpenger
  name: dp-monitor-pods
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dp-monitor-pods
subjects:
  - kind: ServiceAccount
    name: dp-kafka-connect-operator
    namespace: teamdagpenger
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: dp-kafka-connect-operator-apiserver
  namespace: teamdagpenger
spec:
  egress:
    - to:
        - ipBlock:
            cidr: 172.16.0.13/32
  podSelector:
    matchLabels:
      app: dp-kafka-connect-operator
  policyTypes:
    - Egress
