apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dp-kafka-connect-operator
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
    apiserver-access: "enabled"
spec:
  image: {{image}}
  port: 9115
  liveness:
    path: "/metrics"
    initialDelay: 1
  readiness:
    path: "/metrics"
    initialDelay: 1
  replicas:
    disableAutoScaling: true
    min: 1
    max: 1
  prometheus:
    enabled: true
    path: /metrics
  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 128Mi
  env:
    - name: DEBUG
      value: "false"
    - name: DEBUG_UNIX_SOCKET
      value: /tmp/shell-operator/debug.socket
    - name: BASE_URL
      value: http://dp-kafka-connect
  accessPolicy:
    outbound:
      rules:
        - application: dp-kafka-connect
