apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: dp-kafka-connect-operator-apiserver
  namespace: teamdagpenger
spec:
  egress:
    - to:
        - ipBlock:
            cidr: 172.16.0.2/32
  podSelector:
    matchLabels:
      app: dp-kafka-connect-operator
  policyTypes:
    - Egress