apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: teamdagpenger
  name: dp-monitor-pods
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dp-monitor-pods
subjects:
- kind: ServiceAccount
  name: dp-kafka-connect-operator
  namespace: teamdagpenger
